// Generated by hfam_push.py --build-app. Public by design: the app subscribes with this key,
// and only the matching private key (Windows Credential Manager on the HFAM PC) can push to it.
window.HFAM_VAPID_PUBLIC = "BCmyQ7ewPx9nINmbMIAsNWQMs8hq0cMmm8hU9oaT6iUt6CfaztA4keuTVlD1c9Pg_IjQ7gW76xwGkdONPPuTc_Y";
